### ISSUE TITLE
Implement /login endpoint for user authentication

### ISSUE THREAD

**Issue by prasenjeet-symon** [prasenjeet-symon/intellectia#1]
## Description: 
As a user, I want to be able to log in to the application using my email and password, so that I can access the features and functionalities of the app.

## Acceptance Criteria:
- The `/login` endpoint should accept a **POST** request with a JSON object containing `email` and `password` fields as the request body.
- The endpoint should validate the input data and check if the email and password match with any existing user in the database.
- If the login is successful, the endpoint should generate a **JWT token** and send it back to the client as a response header or cookie.
- If the login fails, the endpoint should return an appropriate error message and status code.

**Comment by corners2wall** [comment]
@prasenjeet-symon  Assign to me pls
