### ISSUE TITLE
Add Prisma Migration Folders to .gitignore

### ISSUE THREAD

**Issue by prasenjeet-symon** [prasenjeet-symon/intellectia#100]
**Title**: Add Prisma Migration Folders to `.gitignore`

**Description**:
This GitHub issue is created to address the need to add all migration folders located inside the Prisma folder of the server to the `.gitignore` file. Doing so will ensure that new users do not encounter migration-related issues when setting up the Intellectia project.

**Tasks**:
1. **Identify Prisma Migration Folders**:
   - [ ] Identify all the migration folders that are located inside the Prisma folder of the server.

2. **Update `.gitignore` File**:
   - [ ] Modify the `.gitignore` file to include a wildcard entry that covers all migration folders identified in Task 1. This will prevent these folders and their contents from being tracked by Git.

**Acceptance Criteria**:
- The `.gitignore` file is updated to include a wildcard entry for all migration folders inside the Prisma folder of the server.
- Migration folders and their contents are excluded from version control.

**Additional Information**:
- This task is essential to ensure a smoother onboarding experience for new users of the Intellectia project. By excluding migration folders from version control, new users will not encounter migration-related issues when setting up their development environment.

**Comment by sandheep45** [comment]
As of my knowledge, adding migration files to gitignore is not suggested.

**Comment by prasenjeet-symon** [comment]
I think Prisma can generate the migration folder locally from the schema. What do you think?

**Comment by sandheep45** [comment]
I believe migration files are helpful when we want to revert back to some old schema.

**Comment by prasenjeet-symon** [comment]
> I believe migration files are helpful when we want to revert back to some old schema.

I understand but this is not needed currently ( reverting back ). The main problem is this creates errors for many new contributors
