### ISSUE TITLE
Create and Add apiClient.ts to the API Folder

### ISSUE THREAD

**Issue by prasenjeet-symon** [prasenjeet-symon/intellectia#104]
**Title**: Create and Add `apiClient.ts` to the API Folder

**Description**:
This GitHub issue is created to document the task of adding a new file called `apiClient.ts` to the API folder of the React client. The `apiClient.ts` file contains code for initializing an Axios client that will be used for making HTTP requests.

**Tasks**:
1. **Create `apiClient.ts` File**:
   - [ ] Create a new file named `apiClient.ts` in the API folder of the React client.

2. **Add Axios Client Code**:
   - [ ] Add the following code to `apiClient.ts`:
     ```typescript
     import axios, { AxiosInstance } from 'axios';

     export class AxiosClient {
       private static instance: AxiosClient;
       public axiosInstance: AxiosInstance;

       // ... (rest of the code)

     }
     ```

**Acceptance Criteria**:
- The `apiClient.ts` file is created and added to the API folder of the React client.
- The code for initializing an Axios client is added to the `apiClient.ts` file.

**Additional Information**:
- The `apiClient.ts` file will be used for making HTTP requests to the backend API.
- Once this file is added, it will help facilitate communication between the React client and the backend server.

Please let me know if you have any specific details to add or if you'd like any changes to the issue description.

**Comment by Virtual4087** [comment]
Hi can you assign me this?

**Comment by prasenjeet-symon** [comment]
@Virtual4087 Assigned to you. Waiting for PR. Thanks
