### ISSUE TITLE
Implement Google Signup Functionality

### ISSUE THREAD

**Issue by prasenjeet-symon** [prasenjeet-symon/intellectia#126]
**Title:** Implement Google Signup Functionality

**Description:**
This GitHub issue is created to implement Google signup functionality in the Intellectia application. Users should be able to sign up using their Google tokens for authentication.

**Tasks:**
1. **Implement Signup Function:** In the React client, create a signup function called `signupWithGoogle` that accepts a Google token as a parameter.

2. **API Integration:** Inside the `signupWithGoogle` function, make an API request to the server endpoint `/auth/google` with the provided Google token.

3. **Response Handling:** Handle the response from the server, which should provide an authentication result. Ensure that the authentication result is correctly processed.

4. **Testing:** Thoroughly test the `signupWithGoogle` function to verify that users can successfully sign up using their Google tokens.

**Additional Information:**
- This feature enhances user convenience by allowing them to sign up using their Google accounts, reducing the need to remember additional login credentials.

Upon successful completion of this issue, users will have the option to sign up using their Google tokens, expanding the authentication methods available in the Intellectia application.

**Comment by juhandergod** [comment]
hey, can you assign me to this task? more here: https://github.com/prasenjeet-symon/intellectia/issues/128#issuecomment-1753415312

**Comment by prasenjeet-symon** [comment]
Yes! Assigned it to @juhandergod

**Comment by Krriishhhhhh** [comment]
Hey, can u tell me how are we getting this google token, and which library is to be used to implement oAuth 2 @prasenjeet-symon

**Comment by prasenjeet-symon** [comment]
> Hey, can u tell me how are we getting this google token, and which library is to be used to implement oAuth 2 @prasenjeet-symon

There is a react library for google login
