### ISSUE TITLE
 Implement Google Login Functionality

### ISSUE THREAD

**Issue by prasenjeet-symon** [prasenjeet-symon/intellectia#127]
**Title:** Implement Google Login Functionality

**Description:**
This GitHub issue is created to implement Google login functionality in the Intellectia application. Users should be able to log in using their Google tokens for authentication.

**Tasks:**
1. **Implement Login Function:** In the React client, create a login function called `loginWithGoogle` that accepts a Google token as a parameter.

2. **API Integration:** Inside the `loginWithGoogle` function, make an API request to the server endpoint `/auth/google_login` with the provided Google token.

3. **Response Handling:** Handle the response from the server, which should provide an authentication result. Ensure that the authentication result is correctly processed.

4. **Testing:** Thoroughly test the `loginWithGoogle` function to verify that users can successfully log in using their Google tokens.

**Additional Information:**
- This feature enhances user convenience by allowing them to log in using their Google accounts, reducing the need to remember additional login credentials.

Upon successful completion of this issue, users will have the option to log in using their Google tokens, expanding the authentication methods available in the Intellectia application.

**Comment by yallalaraja** [comment]
I can help you on working and contribute to your issue and pls assign me to do this project

**Comment by prasenjeet-symon** [comment]
> I can help you on working and contribute to your issue and pls assign me to do this project

Okay. Waiting for PR. Thanks

**Comment by prasenjeet-symon** [comment]
@yallalaraja Any progress on this issue? If you need suggestions and help just ask it here or in Discord ( you can tag me directly  ). Thanks.

**Comment by Krriishhhhhh** [comment]
Can u assign this to me, I would like to work on this issue @prasenjeet-symon

**Comment by Krriishhhhhh** [comment]
hey, i was wondering why issue #129 and this one are different , wouldn't it be cool if i create the hook first then use that hook for login process rather than creating a separate function.... what do you think

**Comment by prasenjeet-symon** [comment]
> Can u assign this to me, I would like to work on this issue @prasenjeet-symon

Assigned

**Comment by prasenjeet-symon** [comment]
> hey, i was wondering why issue #129 and this one are different , wouldn't it be cool if i create the hook first then use that hook for login process rather than creating a separate function.... what do you think

Yes both are connected , you can work on both simultaneously, if done mention both issue in commit to close that. Thanks

**Comment by Krriishhhhhh** [comment]
@prasenjeet-symon does this app has  authorization credentials?

**Comment by prasenjeet-symon** [comment]
> @prasenjeet-symon does this app has authorization credentials?

Yes that is located in the local env

**Comment by Krriishhhhhh** [comment]
Hey @prasenjeet-symon , can u give me some context to solve this issue, thanks

**Comment by prasenjeet-symon** [comment]
You have to implement the Axios function that token, there is a separate file for all the things axios . Put your function in there @Krriishhhhhh

**Comment by Josue92sr** [comment]
is there still work to do?

**Comment by prasenjeet-symon** [comment]
> is there still work to do?

No, it is done
