### ISSUE TITLE
Create Google Signup Hook

### ISSUE THREAD

**Issue by prasenjeet-symon** [prasenjeet-symon/intellectia#128]
**Title:** Create Google Signup Hook

**Description:**
This GitHub issue is created to develop a hook in the Intellectia application for signing up users using their Google tokens. The hook will facilitate the Google signup process and navigate users to the appropriate page upon successful signup.

**Tasks:**
1. **Create Hook:** Develop a hook named `useSignupWithGoogle` that will be responsible for handling the Google signup process.

2. **Functionality:** Implement the necessary functionality within the `useSignupWithGoogle` hook to initiate the Google signup process when called.

3. **Navigation:** Ensure that the hook provides a method for navigating users to the `/choose-topics` page upon successful signup.

4. **Testing:** Thoroughly test the `useSignupWithGoogle` hook to confirm its proper operation during Google signup.

**Additional Information:**
- The `useSignupWithGoogle` hook will simplify the Google signup process for users and improve the registration experience in the Intellectia application.

Upon successful completion of this issue, the `useSignupWithGoogle` hook will be available for use, enabling users to sign up using their Google tokens with ease.

**Comment by prasenjeet-symon** [comment]
Okay! Assigned successfully

**Comment by juhandergod** [comment]
hey, accidentally asked to assign me to a wrong issue 😄  there was two open tabs on my screens 😄 can you remove me from this task? Would like to work on this https://github.com/prasenjeet-symon/intellectia/issues/126

**Comment by adesh1998** [comment]
I am thinking of working on issue but as per my knowledge google api are paid how should i implement this then?

**Comment by prasenjeet-symon** [comment]
> @prasenjeet-symon I am thinking of working on issue but as per my knowledge google api are paid how should i implement this then?

You have to create a frontend hook, see the sign hook for inspiration.
