### ISSUE TITLE
Create Google Login Hook

### ISSUE THREAD

**Issue by prasenjeet-symon** [prasenjeet-symon/intellectia#129]
**Title:** Create Google Login Hook

**Description:**
This GitHub issue is opened to develop a hook in the Intellectia application for logging in users using their Google tokens. The hook will simplify the Google login process and provide navigation functionality upon successful login.

**Tasks:**
1. **Hook Creation:** Develop a hook named `useLoginWithGoogle` that will handle the Google login process.

2. **Functionality:** Implement the necessary functionality within the `useLoginWithGoogle` hook to initiate the Google login process when invoked.

3. **Navigation:** Ensure that the hook provides a method for navigating users to the `/dashboard` page upon successful login.

4. **Testing:** Conduct comprehensive testing of the `useLoginWithGoogle` hook to verify its correct operation during Google login.

**Additional Information:**
- The `useLoginWithGoogle` hook will streamline the Google login process for users and enhance the login experience within the Intellectia application.

Upon successful completion of this issue, the `useLoginWithGoogle` hook will be available for use, enabling users to log in using their Google tokens effortlessly.

**Comment by Shouvik11-b** [comment]
hey @prasenjeet-symon  can you assign this task to me?

**Comment by prasenjeet-symon** [comment]
Assigned successfully 🎉 @Shouvik11-b
