### ISSUE TITLE
Implement `shadcn/ui` Form with Zod Validation in Login Page

### ISSUE THREAD

**Issue by prasenjeet-symon** [prasenjeet-symon/intellectia#145]
**Title:** Implement `shadcn/ui` Form with Zod Validation in Login Page

**Description:**
This GitHub issue is created to implement the `shadcn/ui` Form component with Zod validation in the login page of the Intellectia React client. The primary objective is to enhance the user experience and security by using the same approach that was applied to the signup page. The location of the file where the changes need to be made is 'Authentication/LoginPage'.

**Tasks:**
1. **Implement `shadcn/ui` Form:** Integrate the `shadcn/ui` Form component into the login page, replacing the existing form elements.

2. **Zod Validation:** Implement Zod validation for the login form fields, ensuring that both the email and password inputs meet the required validation criteria.

3. **Error Handling:** Implement proper error handling and display error messages to users when validation fails or when there are issues with the login process.

4. **Styling:** Ensure that the login page's appearance is consistent with the rest of the application's design, maintaining a cohesive look and feel.

5. **Testing:** Thoroughly test the login page with the new Form component and Zod validation to verify that it functions correctly and securely.

6. **Documentation:** Update any relevant documentation or comments to reflect the changes made to the login page, including the integration of the `shadcn/ui` Form and Zod validation.

**Additional Information:**
- The changes are to be made in the 'Authentication/LoginPage' file of the Intellectia React client.
- The goal is to provide users with a consistent and user-friendly experience on both the signup and login pages, with proper validation and error handling.

Once this issue is successfully addressed, users will be able to log in securely using the updated login page, benefiting from the integrated `shadcn/ui` Form component and Zod validation. The user experience will be enhanced, and potential errors will be handled gracefully.

**Comment by Rhythm-08** [comment]
Hello ,I would like to solve this issue

**Comment by prasenjeet-symon** [comment]
Assigned!

**Comment by prasenjeet-symon** [comment]
> Hello ,I would like to solve this issue

Hello, @Rhythm-08 can you please update us on your progress? This issue is marked `high priority` and needs resolution as quickly as possible. If you need any support please let us know. Thanks

**Comment by Rhythm-08** [comment]
I will complete it till tonight If I need help I will ping you

**Comment by prasenjeet-symon** [comment]
> I will complete it till tonight If I need help I will ping you. If it's really urgent then you can unassign this task from me. Then I will try some other issues

You can continue. Thanks
