### ISSUE TITLE
Implement Zod Validation for Retrieving a Single Topic by ID

### ISSUE THREAD

**Issue by prasenjeet-symon** [prasenjeet-symon/intellectia#183]
**Title**: Implement Zod Validation for Retrieving a Single Topic by ID

**Description**:
This GitHub issue aims to enhance the validation process for retrieving a single topic by ID within the `src/api/index.ts` file, specifically in the `/topic/:id` route. The task involves implementing Zod validation to ensure the validity of the topic ID parameter and provide a more robust and structured validation approach while removing the old JavaScript validation.

**Tasks**:
1. **Implement Zod Validation**:
   - [ ] Implement Zod validation for the `/topic/:id` route within the `src/api/index.ts` file.
   - [ ] Define the validation logic using Zod to ensure the `id` parameter is required and cannot be 0.

**Acceptance Criteria**:
- The `/topic/:id` route within the `src/api/index.ts` file successfully implements Zod validation for topic ID.
- The validation ensures that the `id` parameter is required and cannot be 0.
- The old JavaScript validation is removed.

**Additional Information**:
- Implementing Zod validation enhances the reliability and maintainability of the code.
- The use of structured validation techniques provides a better user experience and minimizes errors.
- This enhancement contributes to the overall codebase quality.

**Comment by sparsh-18** [comment]
Hello, I would like to work on this. Please assign it to me.
Attached some cases I worked on
![image](https://github.com/prasenjeet-symon/intellectia/assets/60043423/6556a345-caf8-4e7f-8896-b3f44f0079e5)
![image](https://github.com/prasenjeet-symon/intellectia/assets/60043423/b71bfa8b-0a88-4362-aba7-22ec87e052c3)

**Comment by prasenjeet-symon** [comment]
@sparsh-18 Assigned to you

**Comment by sparsh-18** [comment]
[PR added](https://github.com/prasenjeet-symon/intellectia/pull/190)
