### ISSUE TITLE
Implement Zod Validation for Adding Article Series

### ISSUE THREAD

**Issue by prasenjeet-symon** [prasenjeet-symon/intellectia#186]
**Title**: Implement Zod Validation for Adding Article Series

**Description**:
This GitHub issue focuses on enhancing the validation process for adding article series within the `/user/article_series` route. The task involves implementing Zod validation to ensure the validity of the `title` field. Implementing Zod validation contributes to maintaining data integrity and code quality.

**Tasks**:
1. **Implement Zod Validation for `title` Field**:
   - [ ] Implement Zod validation for the `title` field in the `/user/article_series` route.
   - [ ] Define the validation logic using Zod to require the `title` field and ensure it's not empty.

**Acceptance Criteria**:
- The `/user/article_series` route successfully implements Zod validation for the `title` field.
- The `title` validation ensures it's required and not empty.

**Additional Information**:
- Implementing Zod validation improves data integrity and code quality.
- The structured validation approach contributes to better data handling and error prevention.
- This enhancement helps maintain a robust and reliable codebase.

**Comment by mixamum** [comment]
asign to me
