### ISSUE TITLE
Implement Zod Validation for Deleting Article Series

### ISSUE THREAD

**Issue by prasenjeet-symon** [prasenjeet-symon/intellectia#188]
**Title**: Implement Zod Validation for Deleting Article Series

**Description**:
This GitHub issue focuses on enhancing the validation process for deleting article series within the `/user/article_series/:id` route. The task involves implementing Zod validation to ensure the validity of the `id` parameter, preventing erroneous or malicious requests. Implementing Zod validation contributes to data security and code quality.

**Tasks**:
1. **Implement Zod Validation for `id` Parameter**:
   - [ ] Implement Zod validation for the `id` parameter in the `/user/article_series/:id` route.
   - [ ] Define the validation logic using Zod to require a valid integer `id`.

**Acceptance Criteria**:
- The `/user/article_series/:id` route successfully implements Zod validation for the `id` parameter.
- Validation ensures that the `id` is required and must be a valid integer.

**Additional Information**:
- Implementing Zod validation enhances data security and code quality.
- Validating the `id` parameter prevents erroneous or malicious requests.
- This enhancement contributes to maintaining a secure and reliable codebase.

**Comment by mixamum** [comment]
I would love to work on this issue, I had experience with zod in my past projects

**Comment by prasenjeet-symon** [comment]
@mixamum Assigned to you

**Comment by prasenjeet-symon** [comment]
> I would love to work on this issue, I had experience with zod in my past projects

Hello @mixamum If you need help or got stuck do not hesitate to ask us for help on Discord or here. Thanks

**Comment by sparsh-18** [comment]
Hi @prasenjeet-symon, is this issue still open?
