### ISSUE TITLE
Implement /signup endpoint for user registration

### ISSUE THREAD

**Issue by prasenjeet-symon** [prasenjeet-symon/intellectia#2]
## Description: 
As a user, I want to be able to sign up to the application using my email and password, so that I can create an account and access the features and functionalities of the app.

## Acceptance Criteria:
- The `/signup` endpoint should accept a **POST** request with a JSON object containing `email` and `password` fields as the request body.
- The endpoint should validate the input data and check if the email is unique and the password is strong enough.
- If the input data is valid, the endpoint should create a new user in the database with the email and password, and optionally other fields such as name, role, etc.
- If the user creation is successful, the endpoint should generate a **JWT token** and send it back to the client as a response header or cookie.
- If the user creation fails, the endpoint should return an appropriate error message and status code.

**Comment by corners2wall** [comment]
@prasenjeet-symon  Assign to me pls

**Comment by prasenjeet-symon** [comment]
@corners2wall Thank you for expressing your interest in this project. We highly appreciate your enthusiasm and willingness to contribute. To stay updated on new issues, please enable notifications for this repository. We eagerly anticipate your valuable contributions and look forward to collaborating with you.
