### ISSUE TITLE
Password field is visible in signup page

### ISSUE THREAD

**Issue by adesh1998** [prasenjeet-symon/intellectia#221]
**Describe the bug**
It not a major issue but it would be better practice to hide password fields. I would like to go ahead and work on this 

**To Reproduce**
1. Go to signup page
2. Click on password field 

**Expected behavior**
password field should be hidden

**Screenshots**
<img width="587" alt="Screenshot 2023-11-20 at 8 24 51 PM" src="https://github.com/prasenjeet-symon/intellectia/assets/50673082/d48fb228-5804-4d55-993f-ce92be6734e6">

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by adesh1998** [comment]
I would like to work on this further and make changes necessary changes

**Comment by prasenjeet-symon** [comment]
> I would like to work on this further and make changes necessary changes

Yes sounds awesome. Thanks
