### ISSUE TITLE
Add API Route to Get Likes/Dislikes of an Article with Pagination

### ISSUE THREAD

**Issue by prasenjeet-symon** [prasenjeet-symon/intellectia#48]
**GitHub Issue: Add API Route to Get Likes/Dislikes of an Article with Pagination**

**Objective:** Develop an API route that allows users to retrieve the likes or dislikes of a specific article with pagination in our application.

**Description:**

**Tasks:**

1. **Create API Route for Getting Likes/Dislikes of an Article:**
   - Develop a new API route, e.g., `/api/user/article/:id/likes/:status/:size/:cursor`, to enable users to fetch and return the likes or dislikes of a specific article with pagination.
   - Implement the necessary logic to retrieve the likes or dislikes based on the article ID, status (e.g., "liked" or "disliked"), page size (`size`), and cursor for pagination.

2. **Validation:**
   - Implement validation to ensure that the provided article ID, status, `size`, and `cursor` parameters are valid.
   - Verify that the article with the provided ID exists.

3. **Database Interaction:**
   - Integrate the API route with Prisma or our chosen database library to fetch a paginated list of likes or dislikes for the specified article.

4. **Pagination:**
   - Implement pagination to handle large datasets of likes or dislikes effectively. Allow users to specify the page size (`size`) and provide a cursor for paginating through the likes or dislikes.

5. **User Experience:**
   - Ensure clear and user-friendly responses for successful retrieval of likes or dislikes and any potential errors.

**Acceptance Criteria:**

- Users can retrieve the likes or dislikes of a specific article with pagination based on the provided article ID, status, page size (`size`), and cursor using the `/api/user/article/:id/likes/:status/:size/:cursor` route.
- Validation is in place to ensure the provided article ID, status, `size`, and `cursor` are valid, and the article exists.
- The API fetches and returns a paginated list of likes or dislikes for the specified article.
- Pagination is implemented to handle large like or dislike datasets effectively.
- Proper error handling is in place for any issues during like or dislike retrieval.

**Comment by Vayras** [comment]
hey @prasenjeet-symon I would like to work with on this issue , but upon running **_ts-node-dev --respawn src/index.ts_** I encounter a few issues can you help me resolve these so I can work on creating the api endpoint , thanks

**Comment by prasenjeet-symon** [comment]
@Vayras Thank you for expressing your interest in this project. We highly appreciate your enthusiasm and willingness to contribute. To stay updated on new issues, please enable notifications for this repository. We eagerly anticipate your valuable contributions and look forward to collaborating with you.
