### ISSUE TITLE
Implement Node.js Event Listener for Sequential Tasks

### ISSUE THREAD

**Issue by prasenjeet-symon** [prasenjeet-symon/intellectia#62]
**GitHub Issue: Implement Node.js Event Listener for Sequential Tasks**

**Objective:** Develop a Node.js event listener to handle tasks that occur sequentially after a modification API call in our application.

**Description:**

**Tasks:**

1. **Create Event Listener:**
   - Develop a Node.js event listener that listens for events triggered after a modification API call.
   - The event listener should be capable of handling sequential tasks that need to be executed in response to the API call.

2. **Event Handling Logic:**
   - Implement the necessary logic within the event listener to process tasks sequentially.
   - Ensure that tasks are executed in the correct order and that they depend on the successful completion of the previous task.

3. **Integration with Modification API:**
   - Integrate the event listener with the modification API to trigger events and initiate sequential task processing.

4. **Error Handling:**
   - Implement error handling and retries for failed tasks to ensure robustness in handling sequential tasks.

**Acceptance Criteria:**

- A Node.js event listener is created to handle sequential tasks triggered after a modification API call.
- The event listener effectively processes tasks sequentially in the correct order.
- Tasks are dependent on the successful completion of previous tasks.
- The event listener is integrated with the modification API to trigger events.
- Proper error handling and retries are in place for failed tasks.

**Comment by vishesh-hue** [comment]
assign me this issue

**Comment by prasenjeet-symon** [comment]
> assign me this issue

Please read the acceptance criteria carefully before posting the PR. Happy to have you on board.

**Comment by vishesh-hue** [comment]
what should be the path of this eent listner file or where should i implement the logic for the event listner

**Comment by prasenjeet-symon** [comment]
> What should be the path of this event listener file or where should I implement the logic for the event listener

Please check the `events` folder ( index.ts ). It would help if you implemented your logic there.

**Comment by vishesh-hue** [comment]
thanks for it i will start right now !
