### ISSUE TITLE
Integrate Article Story Task with Node.js Task Listener

### ISSUE THREAD

**Issue by prasenjeet-symon** [prasenjeet-symon/intellectia#63]
**GitHub Issue: Integrate Article Story Task with Node.js Task Listener**

**Objective:** Develop a task for creating an article story that will be integrated with a Node.js task listener. This task should be emitted and executed after a modification API call indicating a successful article publication.

**Description:**

**Tasks:**

1. **Create Article Story Task:**
   - Develop a task named `CreateArticleStory` that accepts the `articleId` as a parameter.
   - This task will be responsible for creating an article story after the successful publishing of the article by the author.

2. **Node.js Task Listener:**
   - Implement a Node.js task listener that listens for events triggered after a modification API call, specifically after successful article publication.
   - Integrate the `CreateArticleStory` task with the task listener to emit and execute the task when the API call is made.

3. **Task Execution Logic:**
   - Within the `CreateArticleStory` task, implement the logic to create an article story based on the provided `articleId`.
   - Ensure that the task execution logic follows best practices and includes appropriate error handling.

**Acceptance Criteria:**

- The `CreateArticleStory` task is implemented and accepts the `articleId` as a parameter.
- A Node.js task listener is developed and integrated with the modification API to listen for events.
- The `CreateArticleStory` task is emitted and executed automatically after a successful article publication API call.
- An article story is created for each and every article published on the platform.
- Proper error handling is in place to address any exceptions or issues during the task execution.

**Comment by sandheep45** [comment]
Hey @prasenjeet-symon I need some context for this task. How this `CreateArticleStory` is expected to create an `article` with just `articleId` and `email`. There are various other fields requied as well. How to get these values in the function `CreateArticleStory`

![image](https://github.com/prasenjeet-symon/intellectia/assets/105055197/962b7c0b-45eb-4b67-9534-95e62878938a)

**Comment by prasenjeet-symon** [comment]
You have the email and article ID, where the email belongs to the logged-in user, who is also the article owner (as only they can mark the article as published). When the article is marked as published, an event triggers and calls your function with the email and article ID.

You can follow this path:

```
user[find by email].article.story.[create].{your data }
```

For now, you'll fill the "story" property with the article's subTitle. Later on, we will summarize the full article and use it. Please note that you'll need to fetch the full article once for this purpose.

**Comment by prasenjeet-symon** [comment]
Leave the `storyFor` empty that is part of story distribution

**Comment by sandheep45** [comment]
So first I need to get the `article` then use it's `subTitle` property as the value for `story` field of the `articleStory`. Is this what you mean?

**Comment by prasenjeet-symon** [comment]
> So first I need to get the `article` then use it's `subTitle` property as the value for `story` field of the `articleStory`. Is this what you mean?

Yes for now later AI summary.
