### ISSUE TITLE
Create Task to Distribute Article Story to Author's Followers

### ISSUE THREAD

**Issue by prasenjeet-symon** [prasenjeet-symon/intellectia#64]
**GitHub Issue: Create Task to Distribute Article Story to Author's Followers**

**Objective:** Develop a task that distributes the article story among the followers of the article's author. This task should run automatically after the article's story is created successfully.

**Description:**

**Tasks:**

1. **Create Distribution Task:**
   - Develop a task named `DistributeArticleStory` that accepts the `articleId` as a parameter.
   - This task will be responsible for distributing the article story to the followers of the article's author.

2. **Task Execution Logic:**
   - Within the `DistributeArticleStory` task, implement the logic to identify the author of the article and their followers.
   - Distribute the article story to the identified followers, ensuring that they receive and can access the story.

3. **Integration with Article Story Creation:**
   - Integrate the `DistributeArticleStory` task with the article story creation process so that it runs automatically after the article's story is successfully created.

4. **Error Handling:**
   - Implement error handling within the task to handle any exceptions or issues that may occur during the distribution process.

**Acceptance Criteria:**

- The `DistributeArticleStory` task is implemented and accepts the `articleId` as a parameter.
- The task identifies the author of the article and their followers.
- The article story is distributed successfully to the identified followers.
- The task runs automatically after the article's story is created.
- Proper error handling is in place to address any exceptions or issues during the distribution process.

**Comment by sandheep45** [comment]
@prasenjeet-symon What is meant by `distributing`? Is it like sending any notification?

**Comment by prasenjeet-symon** [comment]
> @prasenjeet-symon What is meant by `distributing`? Is it like sending any notification?

It is not about sending a notification of any kind. It is about adding the article story per user to the database so that any user can fetch their corresponding article stories that are currently active ( not expired ). I hope this makes sense.

**Comment by patilanuja** [comment]
@prasenjeet-symon Can you assign this to me. I would like to work on this issue.

**Comment by prasenjeet-symon** [comment]
> @prasenjeet-symon Can you assign this to me. I would like to work on this issue.

Yes, assigned to you

**Comment by patilanuja** [comment]
Sure, I will start working on this.
Thank you.
