### ISSUE TITLE
Create Task to Add Author to Suggested Users to Follow

### ISSUE THREAD

**Issue by prasenjeet-symon** [prasenjeet-symon/intellectia#65]
**GitHub Issue: Create Task to Add Author to Suggested Users to Follow**

**Objective:** Develop a task that adds the author of an article to the suggested users to follow for the logged-in user. This task should run automatically after positive actions (comments, likes, and saves) are created for the article.

**Description:**

**Tasks:**

1. **Create Suggested User Task:**
   - Develop a task named `AddSuggestedUserToFollow` that accepts the `articleId` as a parameter.
   - This task will be responsible for adding the author of the article to the suggested users to follow for the logged-in user.

2. **Task Execution Logic:**
   - Within the `AddSuggestedUserToFollow` task, implement the logic to identify the author of the article and the logged-in user.
   - Add the author to the suggested users to follow for the logged-in user.

3. **Integration with Positive Actions:**
   - Integrate the `AddSuggestedUserToFollow` task with the positive actions creation process (comments, likes, and saves) so that it runs automatically after these actions are created.

4. **Error Handling:**
   - Implement error handling within the task to handle any exceptions or issues that may occur during the addition of the suggested user.

**Acceptance Criteria:**

- The `AddSuggestedUserToFollow` task is implemented and accepts the `articleId` as a parameter.
- The task identifies the author of the article and the logged-in user.
- The author is added to the suggested users to follow for the logged-in user after positive actions (comments, likes, and saves) are created for the article.
- The task runs automatically after positive actions are created.
- Proper error handling is in place to address any exceptions or issues during the addition of the suggested user.

**Comment by sandheep45** [comment]
@prasenjeet-symon Is the `User` entity **Author** of the `Article` model?

**Comment by prasenjeet-symon** [comment]
> @prasenjeet-symon Is the `User` entity **Author** of the `Article` model?

Yes!

**Comment by sandheep45** [comment]
You can close this

**Comment by prasenjeet-symon** [comment]
> You can close this

Yes! Thanks for letting me know.
