### ISSUE TITLE
Create Task to Add Like Activity to Logged-In User

### ISSUE THREAD

**Issue by prasenjeet-symon** [prasenjeet-symon/intellectia#66]
**GitHub Issue: Create Task to Add Like Activity to Logged-In User**

**Objective:** Develop a task that adds a like activity to the logged-in user's activity feed. This task should run automatically after a like is created successfully for an article.

**Description:**

**Tasks:**

1. **Create Like Activity Task:**
   - Develop a task named `AddLikeActivity` that accepts the `articleId` as a parameter.
   - This task will be responsible for adding a like activity to the logged-in user's activity feed.

2. **Task Execution Logic:**
   - Within the `AddLikeActivity` task, implement the logic to identify the article for which the like was created and the logged-in user.
   - Add the like activity to the logged-in user's activity feed.

3. **Integration with Like Creation:**
   - Integrate the `AddLikeActivity` task with the like creation process so that it runs automatically after a like is created successfully for an article.

4. **Error Handling:**
   - Implement error handling within the task to handle any exceptions or issues that may occur during the addition of the like activity.

**Acceptance Criteria:**

- The `AddLikeActivity` task is implemented and accepts the `articleId` as a parameter.
- The task identifies the article for which the like was created and the logged-in user.
- A like activity is added to the logged-in user's activity feed after a like is created successfully for an article.
- The task runs automatically after a like is created.
- Proper error handling is in place to address any exceptions or issues during the addition of the like activity.

**Comment by dhaneshragu** [comment]
i would like to work on this
