### ISSUE TITLE
Create Task to Add Dislike Activity to Logged-In User

### ISSUE THREAD

**Issue by prasenjeet-symon** [prasenjeet-symon/intellectia#67]
**GitHub Issue: Create Task to Add Dislike Activity to Logged-In User**

**Objective:** Develop a task that adds a dislike activity to the logged-in user's activity feed. This task should run automatically after a dislike is created successfully for an article.

**Description:**

**Tasks:**

1. **Create Dislike Activity Task:**
   - Develop a task named `AddDislikeActivity` that accepts the `articleId` as a parameter.
   - This task will be responsible for adding a dislike activity to the logged-in user's activity feed.

2. **Task Execution Logic:**
   - Within the `AddDislikeActivity` task, implement the logic to identify the article for which the dislike was created and the logged-in user.
   - Add the dislike activity to the logged-in user's activity feed.

3. **Integration with Dislike Creation:**
   - Integrate the `AddDislikeActivity` task with the dislike creation process so that it runs automatically after a dislike is created successfully for an article.

4. **Error Handling:**
   - Implement error handling within the task to handle any exceptions or issues that may occur during the addition of the dislike activity.

**Acceptance Criteria:**

- The `AddDislikeActivity` task is implemented and accepts the `articleId` as a parameter.
- The task identifies the article for which the dislike was created and the logged-in user.
- A dislike activity is added to the logged-in user's activity feed after a dislike is created successfully for an article.
- The task runs automatically after a dislike is created.
- Proper error handling is in place to address any exceptions or issues during the addition of the dislike activity.

**Comment by dhaneshragu** [comment]
i would like to work on this

**Comment by prasenjeet-symon** [comment]
> Acceptance Criteria:

Please read the `Acceptance Criteria:` carefully before submitting the PR. Thanks!
