### ISSUE TITLE
 Create Task to Add Comment Activity to Logged-In User

### ISSUE THREAD

**Issue by prasenjeet-symon** [prasenjeet-symon/intellectia#69]
**GitHub Issue: Create Task to Add Comment Activity to Logged-In User**

**Objective:** Develop a task that adds a comment activity to the logged-in user's activity feed. This task should run automatically after a comment is created successfully for an article.

**Description:**

**Tasks:**

1. **Create Comment Activity Task:**
   - Develop a task named `AddCommentActivity` that accepts the `articleId` as a parameter.
   - This task will be responsible for adding a comment activity to the logged-in user's activity feed.

2. **Task Execution Logic:**
   - Within the `AddCommentActivity` task, implement the logic to identify the article for which the comment was created and the logged-in user.
   - Add the comment activity to the logged-in user's activity feed.

3. **Integration with Comment Creation:**
   - Integrate the `AddCommentActivity` task with the comment creation process so that it runs automatically after a comment is created successfully for an article.

4. **Error Handling:**
   - Implement error handling within the task to handle any exceptions or issues that may occur during the addition of the comment activity.

**Acceptance Criteria:**

- The `AddCommentActivity` task is implemented and accepts the `articleId` as a parameter.
- The task identifies the article for which the comment was created and the logged-in user.
- A comment activity is added to the logged-in user's activity feed after a comment is created successfully for an article.
- The task runs automatically after a comment is created.
- Proper error handling is in place to address any exceptions or issues during the addition of the comment activity.

**Comment by VividhPandey003** [comment]
I would like to work on this under Hacktoberfest. If I face any issues, I hope I can contact you. 
Thanks

**Comment by prasenjeet-symon** [comment]
> I would like to work on this under Hacktoberfest. If I face any issues, I hope I can contact you. Thanks

Yes, you can, and thanks for showing interest in this project. Please read the `Acceptance Criteria` before submitting the PR. If facing any issues or need help just let me know. Thanks!

**Comment by VividhPandey003** [comment]
update: still working on it

**Comment by prasenjeet-symon** [comment]
> update: still working on it

Okay! Take your time.

**Comment by prasenjeet-symon** [comment]
@VividhPandey003 If you are facing any problems or need assistance, please don't hesitate to reach out.

**Comment by VividhPandey003** [comment]
Hey @prasenjeet-symon thanks for your concern, I'd want to figure this out once on my own. If I'm not able to...I'll surely contact you. Thanks for being so welcoming.

**Comment by sandheep45** [comment]
you can close this
