### ISSUE TITLE
Create Task to Add Article Created Activity to Logged-In User

### ISSUE THREAD

**Issue by prasenjeet-symon** [prasenjeet-symon/intellectia#70]
**GitHub Issue: Create Task to Add Article Created Activity to Logged-In User**

**Objective:** Develop a task that adds an article created activity to the logged-in user's activity feed. This task should run automatically after an article is created successfully.

**Description:**

**Tasks:**

1. **Create Article Created Activity Task:**
   - Develop a task named `AddArticleCreatedActivity` that accepts the `articleId` as a parameter.
   - This task will be responsible for adding an article created activity to the logged-in user's activity feed.

2. **Task Execution Logic:**
   - Within the `AddArticleCreatedActivity` task, implement the logic to identify the newly created article and the logged-in user.
   - Add the article created activity to the logged-in user's activity feed.

3. **Integration with Article Creation:**
   - Integrate the `AddArticleCreatedActivity` task with the article creation process so that it runs automatically after an article is created successfully.

4. **Error Handling:**
   - Implement error handling within the task to handle any exceptions or issues that may occur during the addition of the article created activity.

**Acceptance Criteria:**

- The `AddArticleCreatedActivity` task is implemented and accepts the `articleId` as a parameter.
- The task identifies the newly created article and the logged-in user.
- An article created activity is added to the logged-in user's activity feed after an article is created successfully.
- The task runs automatically after an article is created.
- Proper error handling is in place to address any exceptions or issues during the addition of the article created activity.

**Comment by sandheep45** [comment]
you can close this
